import { useState } from "react";
import { Layout } from "@/components/Layout";
import { PageHeader } from "@/components/PageHeader";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useLocation } from "wouter";
import type { Interaction, Customer, Contact } from "@shared/schema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Plus, Phone, Mail, MapPin, Video, MessageCircle, ArrowUpRight, ArrowDownLeft, Bell, Bot, Pencil, Trash2, Search, Filter, FileText, ClipboardList, FilePlus, FileEdit, ListTodo } from "lucide-react";
import { Link } from "wouter";
import { InlineConfirmButton } from "@/components/InlineConfirm";

const INTERACTION_TYPES = [
  { value: "email", label: "Email", icon: Mail },
  { value: "phone_call", label: "Phone Call", icon: Phone },
  { value: "visit", label: "Visit", icon: MapPin },
  { value: "whatsapp", label: "WhatsApp", icon: MessageCircle },
  { value: "video_call", label: "Video Call", icon: Video },
  { value: "offer_created", label: "Offerta creata", icon: FilePlus },
  { value: "offer_versioned", label: "Nuova versione offerta", icon: FileEdit },
  { value: "todo", label: "To Do", icon: ListTodo },
];

const DIRECTIONS = [
  { value: "outbound", label: "Outbound", icon: ArrowUpRight },
  { value: "inbound", label: "Inbound", icon: ArrowDownLeft },
];

const CLASSIFICATIONS = [
  { value: "commercial", label: "Commerciale" },
  { value: "commercial:invio_offerta", label: "Commerciale – Invio Offerta" },
  { value: "commercial:follow_up", label: "Commerciale – Follow Up" },
  { value: "commercial:trattativa", label: "Commerciale – Trattativa" },
  { value: "technical", label: "Tecnico" },
  { value: "technical:assistenza", label: "Tecnico – Assistenza" },
  { value: "technical:installazione", label: "Tecnico – Installazione" },
  { value: "technical:formazione", label: "Tecnico – Formazione" },
  { value: "administrative", label: "Amministrativo" },
];

type InteractionWithNames = Interaction & { customerName?: string; contactName?: string; offerReference?: string; jobOrderReference?: string };

function getTypeIcon(type: string) {
  const t = INTERACTION_TYPES.find(i => i.value === type);
  return t ? t.icon : Mail;
}

function getTypeLabel(type: string) {
  return INTERACTION_TYPES.find(i => i.value === type)?.label || type;
}

function getClassificationLabel(c: string | null | undefined) {
  if (!c) return "";
  return CLASSIFICATIONS.find(cl => cl.value === c)?.label || c;
}

export function InteractionList({
  interactions,
  onEdit,
  onDelete,
  showCompany = true,
}: {
  interactions: InteractionWithNames[];
  onEdit?: (i: InteractionWithNames) => void;
  onDelete?: (id: number) => void;
  showCompany?: boolean;
}) {
  if (interactions.length === 0) {
    return (
      <div className="text-center py-12 text-muted-foreground" data-testid="empty-interactions">
        No interactions found
      </div>
    );
  }

  return (
    <div className="space-y-2">
      {interactions.map(interaction => {
        const TypeIcon = getTypeIcon(interaction.type);
        const isInbound = interaction.direction === "inbound";
        const hasReminder = interaction.reminders && interaction.reminders.length > 0;

        return (
          <div
            key={interaction.id}
            className="flex items-start gap-4 p-4 rounded-xl border border-border bg-card hover:border-primary/20 transition-colors"
            data-testid={`interaction-row-${interaction.id}`}
          >
            <div className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 ${
              isInbound ? "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400" : "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400"
            }`}>
              <TypeIcon className="w-5 h-5" />
            </div>

            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-medium text-foreground">{getTypeLabel(interaction.type)}</span>
                <Badge variant="outline" className="text-xs">
                  {isInbound ? <ArrowDownLeft className="w-3 h-3 mr-1" /> : <ArrowUpRight className="w-3 h-3 mr-1" />}
                  {isInbound ? "Inbound" : "Outbound"}
                </Badge>
                {interaction.autoGenerated && (
                  <Badge variant="secondary" className="text-xs">
                    <Bot className="w-3 h-3 mr-1" />Auto
                  </Badge>
                )}
                {hasReminder && (
                  <Bell className="w-3.5 h-3.5 text-amber-500" />
                )}
                {interaction.classification && (
                  <Badge variant="outline" className="text-xs">{getClassificationLabel(interaction.classification)}</Badge>
                )}
                {interaction.offerReference && (
                  <Badge variant="outline" className="text-xs text-violet-600 border-violet-200 dark:text-violet-400 dark:border-violet-800">
                    <FileText className="w-3 h-3 mr-1" />
                    {interaction.offerReference}
                  </Badge>
                )}
                {interaction.jobOrderReference && (
                  <Badge variant="outline" className="text-xs text-blue-600 border-blue-200 dark:text-blue-400 dark:border-blue-800">
                    <ClipboardList className="w-3 h-3 mr-1" />
                    {interaction.jobOrderReference}
                  </Badge>
                )}
              </div>

              <div className="flex items-center gap-3 mt-1 text-sm text-muted-foreground">
                <span>{new Date(interaction.date).toLocaleString()}</span>
                {showCompany && interaction.customerName && (
                  <span className="font-medium text-foreground">{interaction.customerName}</span>
                )}
                {interaction.contactName && (
                  <span>{interaction.contactName}</span>
                )}
              </div>

              {interaction.notes && (
                <p className="text-sm text-muted-foreground mt-1 line-clamp-2">{interaction.notes}</p>
              )}
            </div>

            {(onEdit || onDelete) && (
              <div className="flex items-center gap-1 shrink-0">
                {onEdit && (
                  <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => onEdit(interaction)} data-testid={`button-edit-interaction-${interaction.id}`}>
                    <Pencil className="w-4 h-4" />
                  </Button>
                )}
                {onDelete && (
                  <InlineConfirmButton
                    title="Delete?"
                    confirmLabel="Delete"
                    onConfirm={() => onDelete(interaction.id)}
                    buttonContent={<Trash2 className="w-4 h-4" />}
                    buttonVariant="ghost"
                    buttonSize="icon"
                    buttonClassName="h-8 w-8 text-destructive"
                    data-testid={`button-delete-interaction-${interaction.id}`}
                  />
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function Interactions() {
  const { toast } = useToast();
  const [, setLocation] = useLocation();
  const [filterType, setFilterType] = useState("");
  const [filterDirection, setFilterDirection] = useState("");
  const [searchText, setSearchText] = useState("");

  const queryParams = new URLSearchParams();
  if (filterType) queryParams.set("type", filterType);
  if (filterDirection) queryParams.set("direction", filterDirection);

  const { data: interactions = [], isLoading } = useQuery<InteractionWithNames[]>({
    queryKey: ["/api/interactions?" + queryParams.toString()],
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => apiRequest("DELETE", `/api/interactions/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ predicate: (query) => {
        const key = query.queryKey[0];
        return typeof key === "string" && key.startsWith("/api/interactions");
      }});
      toast({ title: "Interaction deleted" });
    },
  });

  const filtered = searchText
    ? interactions.filter(i =>
        (i.customerName || "").toLowerCase().includes(searchText.toLowerCase()) ||
        (i.contactName || "").toLowerCase().includes(searchText.toLowerCase()) ||
        (i.notes || "").toLowerCase().includes(searchText.toLowerCase())
      )
    : interactions;

  return (
    <Layout>
      <div className="space-y-6">
        <PageHeader
          title="Interactions"
          subtitle="Track all customer interactions"
          actions={
            <Button onClick={() => setLocation("/crm/interactions/new")} data-testid="button-new-interaction">
              <Plus className="w-4 h-4 mr-2" />New Interaction
            </Button>
          }
        />

        <div className="flex items-center gap-3 flex-wrap">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search interactions..."
              value={searchText}
              onChange={e => setSearchText(e.target.value)}
              className="pl-9 w-64"
              data-testid="input-search-interactions"
            />
          </div>
          <Select value={filterType || "all"} onValueChange={v => setFilterType(v === "all" ? "" : v)}>
            <SelectTrigger className="w-40" data-testid="filter-type">
              <Filter className="w-4 h-4 mr-2" />
              <SelectValue placeholder="All types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All types</SelectItem>
              {INTERACTION_TYPES.map(t => (
                <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={filterDirection || "all"} onValueChange={v => setFilterDirection(v === "all" ? "" : v)}>
            <SelectTrigger className="w-40" data-testid="filter-direction">
              <SelectValue placeholder="All directions" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All directions</SelectItem>
              {DIRECTIONS.map(d => (
                <SelectItem key={d.value} value={d.value}>{d.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {isLoading ? (
          <div className="text-center py-12 text-muted-foreground">Loading...</div>
        ) : (
          <InteractionList
            interactions={filtered}
            onEdit={i => setLocation(`/crm/interactions/${i.id}/edit`)}
            onDelete={id => deleteMutation.mutate(id)}
          />
        )}
      </div>
    </Layout>
  );
}
