// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/price-overview/VariantA.tsx": () => import("../components/mockups/price-overview/VariantA.tsx"),
  "./components/mockups/price-overview/VariantB.tsx": () => import("../components/mockups/price-overview/VariantB.tsx"),
  "./components/mockups/price-overview/VariantC.tsx": () => import("../components/mockups/price-overview/VariantC.tsx"),
  "./components/mockups/recap-day/AgendaVerticale.tsx": () => import("../components/mockups/recap-day/AgendaVerticale.tsx"),
  "./components/mockups/recap-day/Costellazione.tsx": () => import("../components/mockups/recap-day/Costellazione.tsx"),
  "./components/mockups/recap-day/LineaMetropolitana.tsx": () => import("../components/mockups/recap-day/LineaMetropolitana.tsx")
};
