export { generateOfferPdf, generatePreviewPdf } from "./documents";
export {
  type FileStorageProvider,
  LocalFileStorageProvider,
  machineImageStorage,
  enquiryAttachmentStorage,
  layoutDrawingStorage,
  shareHubAttachmentStorage,
  drawingsFileStorage,
  drawingAttachmentStorage,
} from "./fileStorage";
export {
  initIntegrations,
  getEmailProvider,
  getCrmProvider,
  getExternalStorageProvider,
  getWebhookProvider,
  dispatchWebhookEvent,
  getIntegrationLogs,
} from "./integrations";
export {
  initAi,
  getAiProvider,
  setAiProvider,
  summarizeEnquiry,
  recommendMachines,
  draftOfferText,
  recommendPresets,
  reviewRisks,
  autoQuote,
  guardConfigSafety,
  generateOfferEmbedding,
  searchSimilarOffers,
  getAiRuns,
  getAiRunById,
  recordAiFeedback,
  getFeedbackForRun,
  getFeedbackStats,
  refreshAllAnalytics,
  refreshForOffer,
} from "./ai";
